networks:
  market-net:
    driver: bridge

services:
  product-db:
    image: postgres:15
    container_name: product-db
    restart: no
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    ports:
      - "5431:5432"
    networks:
      - market-net
    volumes:
      - product-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres:15
    container_name: user-db
    restart: no
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5430:5432"
    networks:
      - market-net
    volumes:
      - user-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:15
    container_name: order-db
    restart: no
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    ports:
      - "5433:5432"
    networks:
      - market-net
    volumes:
      - order-db-data:/var/lib/postgresql/data

  config-server:
    build: ./github-config-server/.
    container_name: config-server
    restart: no
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${GIT_URI}
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: ${GIT_USERNAME}
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${GIT_PASSWORD}
    env_file:
      - .env
    networks:
      - market-net

  discovery-server:
    build: ./discoveryService/.
    container_name: discovery-server
    restart: no
    ports:
      - "8761:8761"
    networks:
      - market-net
    depends_on:
      - config-server

  product-service:
    build: ./productService/.
    container_name: product-service
    restart: no
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/product_db
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: product
    ports:
      - "8080:8080"
    networks:
      - market-net
    depends_on:
      - config-server
      - discovery-server
      - product-db
      - kafka-1
      - kafka-2
      - kafka-3

  user-service:
    build: ./userService/.
    container_name: user-service
    restart: no
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    ports:
      - "8081:8081"
    networks:
      - market-net
    depends_on:
      - config-server
      - discovery-server
      - user-db
      - kafka-1
      - kafka-2
      - kafka-3

  order-service:
    build: ./orderService/.
    container_name: order-service
    restart: no
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order_db
      SPRING_DATASOURCE_USERNAME: order
      SPRING_DATASOURCE_PASSWORD: order
    ports:
      - "8082:8082"
    networks:
      - market-net
    depends_on:
      - config-server
      - product-db
      - discovery-server
      - kafka-1
      - kafka-2
      - kafka-3

  api-gateway:
    build: ./api-gateway/.
    container_name: api-gateway
    restart: no
    ports:
      - "8765:8765"
    networks:
      - market-net
    depends_on:
      - config-server

  kafka-1:
    image: bitnami/kafka:latest
    networks:
      - market-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=myKafkaCluster
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - user-db-data:/server-1/:/bitnami/kafka
  kafka-2:
    image: bitnami/kafka:latest
    networks:
      - market-net
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=myKafkaCluster
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - user-db-data:/server-2/:/bitnami/kafka

  kafka-3:
    image: bitnami/kafka:latest
    networks:
      - market-net
    ports:
      - "9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=myKafkaCluster
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - user-db-data:/server-3/:/bitnami/kafka

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: false
    depends_on:
      - prometheus

volumes:
  product-db-data:
  user-db-data:
  order-db-data:
  kafka-data:

