networks:
  market-net:
    driver: bridge

services:
  config-server:
    build: ./github-config-server/.
    container_name: config-server
    restart: no
    ports:
      - "8888:8888"
    networks:
      - market-net

  discovery-server:
    build: ./discoveryService/.
    container_name: discovery-server
    restart: no
    ports:
      - "8761:8761"
    networks:
      - market-net
    depends_on:
      - config-server

  product-service:
    build: ./productService/.
    container_name: product-service
    restart: no
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/product_db
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: product
    ports:
      - "8080:8080"
    networks:
      - market-net
    depends_on:
      - config-server
      - discovery-server
      - product-db
      - kafka-1
      - kafka-2
      - kafka-3

  user-service:
    build: ./userService/.
    container_name: user-service
    restart: no
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    ports:
      - "8081:8081"
    networks:
      - market-net
    depends_on:
      - config-server
      - discovery-server
      - user-db
      - kafka-1
      - kafka-2
      - kafka-3

  order-service:
    build: ./orderService/.
    container_name: order-service
    restart: no
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order_db
      SPRING_DATASOURCE_USERNAME: order
      SPRING_DATASOURCE_PASSWORD: order
    ports:
      - "8082:8082"
    networks:
      - market-net
    depends_on:
      - config-server
      - product-db
      - discovery-server
      - kafka-1
      - kafka-2
      - kafka-3

  api-gateway:
    build: ./api-gateway/.
    container_name: api-gateway
    restart: no
    ports:
      - "8765:8765"
    networks:
      - market-net
    depends_on:
      - config-server


volumes:
  product-db-data:
  user-db-data:
  order-db-data:

